### PR TITLE
Added the Primeval Guardian Ranger archetype.

### PR DESCRIPTION
**Pull request by Magneseus**
From the 2017 UA: Rangers & Rogues.

### CODE REVIEW

**Comment by chrisjfoss** [comment]
Nice!  I'm not suggesting you need to change it, but an alternative sheet description for Ancient Fortitude could be something along the lines of:
    <sheet>
        <description>
            Your hit point maximum and current hit points increase by %ancient fortitude% when you assume your guardian form. This lasts until you leave the form.
        </description>
    </sheet>
    <rules>
        <stat name="ancient fortitude" value="level:ranger" />
        <stat name="ancient fortitude" value="level:ranger" />
    </rules>
        
This would have the advantage of giving the player the correct number immediately when looking at the sheet, but the disadvantage of obscuring where the actual number is coming from.  There is a similar alternative for Guardian Aura.

For the ones I've been adding, I've had it put in the actual number when relevant, but I think most of the existing ones do it the way you did.

**Comment by Magneseus** [comment]
Oh that's interesting, never considered doing that. I'm honestly fine with either way of doing it. Whatever way @swdriessen prefers I suppose.

**Comment by swdriessen** [comment]
Thanks for the contribution!

I tend to include them so you don't have to do the calculations ingame and to keep sheet descriptions short and to the point. When making the character you can read full description what your features do.

Also, in the future there will be a list of your features so you can view your features in full regardless if they show up on the sheet or not. I also want to enable the user to edit sheet descriptions, but this is all for later.

Quick tip: create a branch when working on something so you can keep different things seperated when submitting pull requests.

**Comment by Magneseus** [comment]
Updated to use the Ranger level on the sheet.
Will branch off in future, gonna be submitting the Artificer class soon which will be on it's own branch.

**Comment by swdriessen** [comment]
Thanks. I'll the skill says 2 per level, so ill add another stat rule to double it. I have to uncomment the line in the UA index anyway.

**Pull request merged**
