### PR TITLE
WIP: Morgrave Miscellany

### PR DESCRIPTION
**Pull request by Azzzzzy**
Added Barbarian Extreme Explorer Path from Morgrave Miscellany. (Originally authored by Belja)
Added Source information for Morgrave Miscellany
Added Index for Morgrave Miscellany
If anyone is curious about the progress: https://docs.google.com/spreadsheets/d/1ep2YSlElIi7lIq0dqg4paVxsItcBu3-tN8-GkLsDTRw/edit?usp=sharing

### CODE REVIEW

**Comment by Azzzzzy** [comment]
Added Warlock Pact Boon: Pact of the Host

**Comment by Azzzzzy** [comment]
Added Bardic College: College of Keys

**Comment by Azzzzzy** [comment]
Added Shifter Subraces: Cliffwalk, Truedive and Swiftwing

**Comment by Azzzzzy** [comment]
Added Backgrounds: Cadet, Chronicler, Aspirant and Auditor

**Comment by Azzzzzy** [comment]
Added Mark of Death Elf Subrace

**Comment by swdriessen** [comment]
I merged the current WIP with index commented out to avoid confusion about incomplete sources. Will check what else from the source are player options that are not included currently.

**Pull request merged**
