### PR TITLE
Human second language fix

### PR DESCRIPTION
**Pull request by dlmorais-13**
Human second language is not restricted to those flagged as starting

### CODE REVIEW

**Comment by NickVendel** [comment]
Why though? I mean, there's probably someone who wants their PC Human to have Abyssal or Primordial. But usually they can change support by themselves.

**Comment by dlmorais-13** [comment]
What do you mean by "change by themselves"?

**Comment by NickVendel** [comment]
Well, like you did, they can go to *\custom\core\players-handbook* and change support in "race-human.xml" file.

**Comment by swdriessen** [comment]
Yes, when the version number gets updated the builder will update and override the existing file. It's not recommended to update existing files if you want these changes to persist.

When you still want to customize the file it's better to make a copy of the file, place it in the root of the custom folder (or better, a secondary folder (see settings)) and only have the element that you want to change left in the file. (same ID overrides the existing element)

Eventually there will ofcourse be a way to change things from the UI, for example a small 'houserule' button in the header of a selection item that allows you to choose any language currently loaded by the application. No ETA for this feature.

**Comment by NickVendel** [comment]
Yes, sure, if there's going to be update to the file. But if you don't want this to happen, i believe you can just copy changed file to the *custom* folder, it will rewrite original file, because everything in custom loads last.

We can discuss this. I don't think it's too hard. Just open file Ctrl+F and look up `supports="Starting"` then just delete it. You're talking with the guy who has almost 0 experience with programming/codding prior to Aurora.

**Pull request closed without merging**
