### PR TITLE
Misc. additions from Planeshift

### PR DESCRIPTION
**Pull request by Azzzzzy**
Added Vampire Race from Ixalan and Zendikar
Added Pyromancer Sorcerous Origin

### CODE REVIEW

**Comment by NickVendel** [comment]
Was requested in #153

**Comment by NickVendel** [comment]
@Azzzzzy it's better to do different pulls for different requests.

**Comment by Azzzzzy** [comment]
Is there any way to do that without making a new fork?

**Comment by NickVendel** [comment]
Not really, yeah.

**Pull request closed without merging**
