### PR TITLE
Added Zeal Domain Cleric

### PR DESCRIPTION
**Pull request by ShadowLinks**
Added Zeal Domain xml to planeshift amonkhet and updated planeshift.index

This is my first attempt, so please let me know if there is anything i can do better.

### CODE REVIEW

**Comment by Azzzzzy** [comment]
I think you grabbed the wrong description for the zeal domain. 
Also a note to make when you use the description on the sheet you can replace wisdom modifier with %Wisdom Modifier% to show the actual number on the sheet.

**Comment by Azzzzzy** [comment]
I've cleaned up some of your descriptions on the cleric-zeal file
[Cleric-zeal.zip](https://github.com/aurorabuilder/elements/files/2905877/Cleric-zeal.zip)

**Comment by swdriessen** [comment]
The file should be named `cleric-zeal.xml` instead of `Cleric-zeal` (also update the url's to reflect this change) — all files/folders are lowercase.

The source attributes in the elements should be named `Plane Shift` instead of `Planeshift` so they fall under the same source for restrictions

And the old `%Wisdom Modifier%` can be replaced with the new `{{wisdom:modifier}}`

**Comment by swdriessen** [comment]
oops, nevermind—i noticed you guys combined them in another pull request

**Comment by swdriessen** [comment]
Combined and merged in 04e51eb1bb0e119decc008057f3695d643054c29

**Pull request closed without merging**
