### PR TITLE
UA Vedalken (Race)

### PR DESCRIPTION
**Pull request by CheshireSwift**
Adding in the Vedalken from UA Plane Shift: Kaladesh.

### CODE REVIEW

**Comment by swdriessen** [comment]
Thanks. I'll take a look at it tonight.

**Comment by swdriessen** [comment]
Two small things: 
- the id for the race says WOCT instead of WOTC (if corrected later it would result in characters not loading correct)
- and you can increment the version of the changed planeshift.index file by 0.0.1 so the builder knows there is a change

I'll merge it when these have been changed.

**Comment by CheshireSwift** [comment]
Good catch on the typo! Changes pushed 🙂

**Comment by swdriessen** [comment]
Thank you!

**Pull request merged**
