### PR TITLE
[UA20170320] Wizard Revisited: Source for Blood Domain changed

### PR DESCRIPTION
**Pull request by NickVendel**
• "Tal’Dorei Campaign Setting" changed to "Critical Role: Tal’Dorei Campaign Setting"

### CODE REVIEW

**Comment by swdriessen** [comment]
You can remove the commented lines instead, i won't be including third-party in the UA playtest material anyway.

**Comment by NickVendel** [comment]
Are you sure, i mean it's easier to remove comment rather than create whole Domain for Wizard, if you want to play it. I could put it somewhere under Critical Role folder, but i'm not sure where and if you okay with that.

**Comment by swdriessen** [comment]
Yeah, i'm sure.

**Comment by NickVendel** [comment]
alright, but what about other idea?
> I could put it somewhere under Critical Role folder, but i'm not sure where and if you okay with that.

**Comment by swdriessen** [comment]
Just remove it. You can homebrew it if you want to mix the playtest material with third-party content.

**Comment by NickVendel** [comment]
Got it, will do then

**Comment by NickVendel** [comment]
@swdriessen it's done

**Pull request merged**
