### PR TITLE
Added School of Invention 

### PR DESCRIPTION
**Pull request by chrisjfoss**
This will complete issue #2.

Reckless casting and arcanomechanical armor together get wordy, resulting in very small text in the sheet at higher levels.

### CODE REVIEW

**Comment by swdriessen** [comment]
I'll check it out. 

A heads up. Next time when adding something, create a new branch to work on it instead of making the changes in your master branch. You see previous commits of circle of spores and such here.

**Comment by swdriessen** [comment]
Since the armor is something you get, you can make an item for it. I just coppied the studded leather and changed it abit. Then the wizard can equip it and the description doesn't have to be so detailed.

You can't 'grant' the armor yet. The users will have to add it manually from the item list.

```
    <element name="Arcanomechanical Armor" type="Item" source="Unearthed Arcana" id="ID_WOTC_UA_ARMOR_LIGHT_ARCANOMECHANICAL">
        <supports>ID_INTERNAL_ARMOR_GROUP_LIGHT</supports>
        <description>
            <p><i>Prerequisite: School of Invention arcane tradition</i></p>
            <p>While you are attuned to it and wearing it, it grants you resistance to force damage.</p>
            <p>The armor is light armor and provides an AC of 12 + your Dexterity modifier. It weighs 8 pounds. You can create a new suit of it at the end of a long rest by touching a nonmagical suit of studded leather armor, which magically transforms it. Doing so removes the magic from your previous arcanomechanical armor, turning it into nonmagical studded leather.</p>
        </description>
        <setters>
            <set name="category">Armor</set>
            <set name="cost" currency="gp">0</set>
            <set name="weight" lb="8">8 lb.</set>
            <set name="container">Light</set>
            <set name="armor">Light</set>
            <set name="weapon" />
            <set name="shield" />
            <set name="slot">body</set>
            <set name="range" />
            <set name="damage" />
        </setters>
        <rules>
            <stat name="AC" value="+2" bonus="Armor"/>
        </rules>
  </element>
```

You can add a level attribute to a sheet description node to have different descriptions / level. This way you can at least hide the higher level lists at levels where they are not relevant anyway.

Like so:
https://github.com/aurorabuilder/elements/blob/573a71bab3ca85f42560a5cac7915ff1a787e9ae/core/players-handbook/races/race-elf.xml#L283-L285

**Comment by chrisjfoss** [comment]
Ah, I had forgotten that I could hide portions of the descriptions.  Can I write the code to grant the armor now, so that it will work once you finish working on supporting equipment, or is the syntax that will be required to do so still uncertain?

**Comment by swdriessen** [comment]
It most likely won't be 'grant' but more like a one time 'add' so just leave a comment in the rules with a todo: to add the armor to inventory.

**Comment by chrisjfoss** [comment]
Added the changes.  Let me know if anything else needs fixed!  I saw your recommendation to prepend the commit messages with the source id, so I will adopt that for future commits.

**Comment by swdriessen** [comment]
I prefer it so you can quickly see what source the commit is for. I can still merge this pull request as one commit when i merge it so that no problem. It takes care of the commits that are confusing or the ones that are 'fix this' or 'quick fix for typo' which just clutter the commit history.

**Pull request merged**
