### PR TITLE
Legends of Runeterra: Dark Tides of Bilgewater

### PR DESCRIPTION
**Pull request by JayPea00101010**
Pretty sure it's all good, I'll change Amour to Armor in the barbarian if you really want, but other thn that fingers crossed it's fine

### CODE REVIEW

**Comment by swdriessen** [comment]
content from dndbeyond is out of the [project scope](https://github.com/aurorabuilder/elements/blob/master/.github/CONTRIBUTING.md#out-of-the-project-scope)

Isn't this some temporary promo from a mobile game? - i'll put it on hold for now, maybe they'll put it on the dmsguild

**Comment by JayPea00101010** [comment]
Oh, I figured it was in scope, with it being company created, not user created.
If not though I can mave a seperate Repo for it

**Comment by swdriessen** [comment]
I'll review it anyway and combine it in 1 file instead of an index (like [this one](https://github.com/aurorabuilder/elements/blob/master/third-party/dms-guild/calimshan-adventurers-guide.xml) for example) since the source is unlikely to ever change.

**Comment by JayPea00101010** [comment]
Sounds fair enough

**Comment by swdriessen** [comment]
This content repository is being archived. I am closing any pending issues and pull requests.
I'll be sharing more information about concrete changes at a later date on the website.

**Pull request closed without merging**
