### PR TITLE
D&D wiki Lamia - JayPea

### PR DESCRIPTION
**Pull request by JayPea00101010**

### CODE REVIEW

**Comment by NickVendel** [comment]
@JayPea00101010 few things:
1. First it's fine leaving author as "D&D Wiki", but maybe you would find main contributors to the article? (and you probably should use `author url` for link to the article) 
2. Articles of D&D Wiki are always changing, so to keep consistency it's preferable to put link to the page version, rather than to article itself. Check my Weapon Master file and find `<set>` with the url to have an example.

**Comment by JayPea00101010** [comment]
sorry, first time making one but yeah I'll get it changed asap

**Comment by JayPea00101010** [comment]
better?
Also changed a couple of file names because the capitalisation was off, not sure if it would've affected anything but baeeter safe than sorry

**Comment by NickVendel** [comment]
Well, better, you fixed 1st issue i had with pull, but you didn't do anything about second issue i had

**Comment by JayPea00101010** [comment]
sorry, I thought I did, my bad

**Comment by JayPea00101010** [comment]
Ok I think its good now

**Comment by NickVendel** [comment]
No, you got right link and `<set>`, but you need to put it in all elements, like in all of them. Again, just like my Weapon Master. So when you click on the link under feature in-app it would send you to that page, rather than to just "D&D Wiki Homebrew" page

**Comment by JayPea00101010** [comment]
ok, sorry it took so long for me to get around to it, Is that better?

**Comment by NickVendel** [comment]
Yeah, this is fine, even better would be to have a link to features themselves in the article, but it's fine either way.

**Comment by swdriessen** [comment]
You can create the pull request in the new repository https://aurorabuilder.com/posts/943/community-driven-contentdnd-wiki/

**Pull request closed without merging**
