### PR TITLE
Placeholder files for COFSA Additions

### PR DESCRIPTION
**Pull request by ColdAnkles**
Added index files and sources for the Compendium  of Forgotten Secrets.

I plan to add to this slowly one-by-one and try to avoid having it all in one big commit.

### CODE REVIEW

**Comment by NickVendel** [comment]
I'm sorry... did you just delete everything existing in dnd-wiki.index?

**Comment by ColdAnkles** [comment]
That was a typo

Link to pirated version?

**Comment by NickVendel** [comment]
Ah, it's free version... then i don't know, i think it's better to just link to website, rather than to .pdf, but if it's a free version then it's fine.

**Comment by swdriessen** [comment]
I'll add the placeholders so they can be used

**Comment by ColdAnkles** [comment]
Should I add the bits Azzzzy and I have done into this PR or into a second one after the placeholders are in?

**Comment by swdriessen** [comment]
I will commit this (with a few minor changes) when i get home. You people then create pull requests for the individual content.

**Pull request merged**
